import './cli.test.js';
import './config.test.js';
import './emit.test.js';
import './lockfile.test.js';
import './plan.test.js';
import './registry.test.js';
import './removal.test.js';
import './status.test.js';
import './sync.test.js';
